[build.environment]
  NODE_VERSION = "18"

[build]
  publish = "dist"
  command = "pnpm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
from = "/"
to = "/home"
status = 200

[[plugins]]
package = "@algolia/netlify-plugin-crawler"
  [plugins.inputs]
  renderJavaScript = true